### PR TITLE
Save load path

### LINKED ISSUE #852: inconsistent support for `pathlib` objects
`metatensor` and `metatensor-torch` don't support `pathlib` objects consistently.

- `metatensor.io.save` does NOT support it (apparently a regression from #548)
- `metatensor.io.load` does
- `metatensor.torch.load` does NOT

```python

import metatensor
from pathlib import Path
import numpy as np

label = metatensor.Labels("_", np.array([[0]]))
block = metatensor.TensorBlock(samples=label, components=[], properties=label, values=np.array([[0]]))
tensor = metatensor.TensorMap(label, [block])

file = Path("foo.bar")
metatensor.io.save(file, tensor)
metatensor.io.load(file)

```

fails already at `.save` with 

```
AttributeError: 'PosixPath' object has no attribute 'endswith'
```

This fails at the last `load`

```python

import metatensor
from pathlib import Path
import numpy as np

label = metatensor.Labels("_", np.array([[0]]))
block = metatensor.TensorBlock(samples=label, components=[], properties=label, values=np.array([[0.0]]))
tensor = metatensor.TensorMap(label, [block])

file = Path("foo.npz")
metatensor.io.save(str(file), tensor)
metatensor.io.load(file)

import metatensor.torch as mt

mt.load(file)
```

My suggestion for a fix would be to forcefully cast all filenames as `str` and proceed from there.

### PR DESCRIPTION
**Pull request by Luthaf**
The first commit fixes a surprising behavior, where the TorchScript compiler would completely remove calls to `mts.save()`, since the function was assumed to have not side-effect.

The second commit fixes #852

# Contributor (creator of pull-request) checklist

 - [x] Tests updated (for new features and bugfixes)?
 - [x] Documentation updated (for new features)?
 - [x] Issue referenced (for PRs that solve an issue)?

# Reviewer checklist

 - [x] CHANGELOG updated with public API or any other important changes?

### CODE REVIEW

File: python/metatensor_torch/metatensor/torch/serialization.py [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+            supported.
+    """
+    if torch.jit.is_scripting():
+        assert isinstance(file, str)
+        return torch.ops.metatensor.load(file=file)
+    else:
+        if isinstance(file, str):
+            return torch.ops.metatensor.load(file=file)
+        elif isinstance(file, pathlib.Path):
+            return torch.ops.metatensor.load(file=str(file))
```
Comment (HaoZeke) [inline python/metatensor_torch/metatensor/torch/serialization.py:50]:
```suggestion
        elif isinstance(file, pathlib.Path):
            return torch.ops.metatensor.load(file=str(file.resolve()))
```

File: python/metatensor_torch/metatensor/torch/serialization.py [hunk 2]
```diff
@@ -0,0 +1,159 @@
...
+        else:
+            # assume a file-like object
+            buffer = file.read()
+            assert isinstance(buffer, bytes)
+
+            buffer = torch.tensor(np.frombuffer(buffer, dtype=np.uint8))
```
Comment (HaoZeke) [inline python/metatensor_torch/metatensor/torch/serialization.py:56]:
```suggestion
            buffer = torch.frombuffer(buffer, dtype=torch.uint8)
```

Also why hard-code the `dtype`?

File: python/metatensor_torch/metatensor/torch/serialization.py [hunk 3]
```diff
@@ -0,0 +1,159 @@
...
+            supported.
+    """
+    if torch.jit.is_scripting():
+        assert isinstance(file, str)
+        return torch.ops.metatensor.load_block(file=file)
+    else:
+        if isinstance(file, str):
+            return torch.ops.metatensor.load_block(file=file)
+        elif isinstance(file, pathlib.Path):
+            return torch.ops.metatensor.load_block(file=str(file))
```
Comment (HaoZeke) [inline python/metatensor_torch/metatensor/torch/serialization.py:83]:
```suggestion
            return torch.ops.metatensor.load_block(file=str(file.resolve()))
```

File: python/metatensor_torch/metatensor/torch/serialization.py [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+        else:
+            # assume a file-like object
+            buffer = file.read()
+            assert isinstance(buffer, bytes)
+
+            buffer = torch.tensor(np.frombuffer(buffer, dtype=np.uint8))
```
Comment (HaoZeke) [inline python/metatensor_torch/metatensor/torch/serialization.py:89]:
```suggestion
            buffer = torch.frombuffer(buffer, dtype=torch.uint8)
```

File: python/metatensor_torch/metatensor/torch/serialization.py [hunk 5]
```diff
@@ -0,0 +1,159 @@
...
+            supported.
+    """
+    if torch.jit.is_scripting():
+        assert isinstance(file, str)
+        return torch.ops.metatensor.load_labels(file=file)
+    else:
+        if isinstance(file, str):
+            return torch.ops.metatensor.load_labels(file=file)
+        elif isinstance(file, pathlib.Path):
+            return torch.ops.metatensor.load_labels(file=str(file))
```
Comment (HaoZeke) [inline python/metatensor_torch/metatensor/torch/serialization.py:114]:
```suggestion
            return torch.ops.metatensor.load_labels(file=str(file.resolve()))
```

File: python/metatensor_torch/metatensor/torch/serialization.py [hunk 6]
```diff
@@ -0,0 +1,159 @@
...
+        else:
+            # assume a file-like object
+            buffer = file.read()
+            assert isinstance(buffer, bytes)
+
+            buffer = torch.tensor(np.frombuffer(buffer, dtype=np.uint8))
```
Comment (HaoZeke) [inline python/metatensor_torch/metatensor/torch/serialization.py:120]:
```suggestion
            buffer = torch.frombuffer(buffer, dtype=torch.uint8)
```

File: python/metatensor_torch/metatensor/torch/serialization.py [hunk 7]
```diff
@@ -0,0 +1,159 @@
...
+    :param data: data to serialize and save
+    """
+    if torch.jit.is_scripting():
+        assert isinstance(file, str)
+        return torch.ops.metatensor.save(file=file, data=data)
+    else:
+        if isinstance(file, str):
+            return torch.ops.metatensor.save(file=file, data=data)
+        elif isinstance(file, pathlib.Path):
+            return torch.ops.metatensor.save(file=str(file), data=data)
```
Comment (HaoZeke) [inline python/metatensor_torch/metatensor/torch/serialization.py:151]:
```suggestion
            return torch.ops.metatensor.save(file=str(file.resolve()), data=data)
```

**Review by HaoZeke — COMMENTED** [review]
Minor nits.

File: metatensor-torch/src/register.cpp [hunk 8]
```diff
@@ -301,7 +301,7 @@ TORCH_LIBRARY(metatensor, m) {
     m.def("dtype_name(ScalarType dtype) -> str", scalar_type_name);
 
     m.def(
-        "load(str path) -> __torch__.torch.classes.metatensor.TensorMap",
+        "load(str file) -> __torch__.torch.classes.metatensor.TensorMap",
```
[the remark this answers is not in the document]
Comment (Luthaf) [reply metatensor-torch/src/register.cpp:304]: we are using `file` everywhere else (because it is either a path or a pre-opened file)

**Review by HaoZeke — APPROVED** [review]
LGTM, thanks @luthaf.
