### ISSUE TITLE
inconsistent support for `pathlib` objects

### ISSUE THREAD

**Issue by sirmarcel** [metatensor/metatensor#852]
`metatensor` and `metatensor-torch` don't support `pathlib` objects consistently.

- `metatensor.io.save` does NOT support it (apparently a regression from #548)
- `metatensor.io.load` does
- `metatensor.torch.load` does NOT

```python

import metatensor
from pathlib import Path
import numpy as np

label = metatensor.Labels("_", np.array([[0]]))
block = metatensor.TensorBlock(samples=label, components=[], properties=label, values=np.array([[0]]))
tensor = metatensor.TensorMap(label, [block])

file = Path("foo.bar")
metatensor.io.save(file, tensor)
metatensor.io.load(file)

```

fails already at `.save` with 

```
AttributeError: 'PosixPath' object has no attribute 'endswith'
```

This fails at the last `load`

```python

import metatensor
from pathlib import Path
import numpy as np

label = metatensor.Labels("_", np.array([[0]]))
block = metatensor.TensorBlock(samples=label, components=[], properties=label, values=np.array([[0.0]]))
tensor = metatensor.TensorMap(label, [block])

file = Path("foo.npz")
metatensor.io.save(str(file), tensor)
metatensor.io.load(file)

import metatensor.torch as mt

mt.load(file)
```

My suggestion for a fix would be to forcefully cast all filenames as `str` and proceed from there.

**Comment by Luthaf** [comment]
This should be a relatively easy fix. The only issue I can foresee would be using `pathlib` in the annotations of the `metatensor-torch` version, since these classes are not compatible with TorchScript.
